### ISSUE TITLE
vscode를 이용해 자바 개발 환경을 세팅해봤습니다.

### ISSUE THREAD

**Issue by Quska45** [Quska45/sunday-spring-study#11]
저번 스터디 시간에 잠깐 얘기 했던 vscode를 이용한 자바 개발환경을 세팅해봤습니다.
제가 사용해본 장/단점에 대해서 몇가지 쓰도록 하겠습니다. 
개인적으로는 단점이 많이 치명적이라고 느껴져서 저는 쓰지 않으려고 합니다.
만약에 보시고 이런 단점이 있더라도 개발환경을 세팅해보고 싶으시다면 도와드리도록 하겠습니다.
근데 기본적인 세팅만 같이 해보고 단점을 개선해주시면 정말 감사할 것 같습니다. 단점을 개선할 수만 있다면 쓰고 싶어요.

#### 장점
1. 이클립스에 비해 빠릅니다.
2. 저는 개인적으로 vscode를 좋아해서 보기가 좋았습니다.

#### 단점
1. 자동 빌드가 되지 않습니다. 매번 빌드툴을 이용해 war파일을 빌드하고 톰캣을 재실행 해야 합니다.
2. html에서 코드를 수정한 사항을 프로젝트 소스에 직접 반영해야 합니다.(복붙해줘야 합니다.) 이유는 빌드된 파일을 수정해야 톰캣이 이것을 인식하고 브라우져에 바로 반영해주는데 빌드된 파일의 수정된 부분을 프로젝트 소스에 바로 반영할 수 있는 방법을 찾지 못했습니다.

**Comment by seokyoung-kim** [comment]
아무래도 java 전용 에디터가 아니다보니 extension만으로는 어렵나보네요.

**Comment by WonYong-Jang** [comment]
vscode가 가볍고 빨라서 좋은데 자동 빌드가 안되는게 가장 크네요..스크립트 한줄 바꿔도 재빌드 해야하나요?

**Comment by Quska45** [comment]
vscode의 extension이 제공하는 기능만 사용한다면 스크립트 한줄을 바꿔도 다시 재빌드 해야 합니다. 톰캣의 설정을 바꿔주면 빌드 할 필요없이 바로 반영이 가능하지만 단점 2번에서 얘기 했듯이 빌드된 파일의 코드를 수정하는 방식으로 개발을 진행해야 하기 때문에 수정된 내용을 프로젝트 파일에 다시반영해 줘야 했습니다.
