### ISSUE TITLE
인텔리제이 커뮤니티(무료) 버전 

### ISSUE THREAD

**Issue by WonYong-Jang** [Quska45/sunday-spring-study#14]
인텔리제이 커뮤니티(무료) 버전을 다운받아 사용해봤습니다.
스프링 부트기반으로 개발하는데 있어서 커뮤니티 버전도 어려움이 없다고 하여
저는 로컬에서 인텔리제이로 개발을 하려고 하는데 리액트와 연동하는데 
혹시 어려움이 있을까요?

인텔리제이 커뮤니티 버전 궁금하신 분들은 아래와 같이 설치가 가능합니다.
- https://jetbrains.com/toolbox/app/ 접속
- 툴박스 실행하여 IntelliJ IDEA Community -> Install 

- - -
인텔리제이를 사용해본 결과
이클립스와 다르게 워크스페이스 개념이 없습니다. 즉 모든 프로젝트를 한 번에 불러오지 못하고
한 화면에 하나의 프로젝트만 열립니다. 
많이 써보진 못했지만 자동완성기능이 빠르고 lombok과 같은 플러그인 추가가 이클립스보다 간편하다고 
느꼈습니다.

**Comment by seokyoung-kim** [comment]
얼티밋 버전과 비교했을때 커뮤니티 버전의 단점이라면
```
1. Spring Initializer가 제공되지 않아서 환경 설정을 개발자가 스스로 해야한다는 점.
2. Javascript 파일에 대한 Syntax Highlighting이 제공되지 않는 점.
```
이 두가지를 들 수 있습니다. 인텔리제이로 리액트를 연동하는 것 자체에는 문제가 없습니다. 다만 자바스크립트 파일에 Syntax Highlighting이 없다는 것이 리액트 코드 작성에 있어 어려움이 있습니다. 따라서 스프링 코드 작성은 인텔리제이로 하되 리액트 코드 작성은 VSC와 같은 툴로 작성하고 나중에 merge하는 것이 생산성에 있어 바람직한 방향이 아닐까 생각합니다.
