### ISSUE TITLE
풀리퀘스트를 요청하실 때 참고하셨으면 하는게 있습니다.

### ISSUE THREAD

**Issue by Quska45** [Quska45/sunday-spring-study#6]
오른쪽에 보시면 Assingenees, Labels, Projects가 있습니다. 사용해 보시면 좋을 것 같습니다.
Milestone은 뭔지 모르겠고 Linked pull requests는 써본 적이 없는데 이번에 활용해 보면 좋겠습니다.
그리고 스터디 시간에 일주일 동안 작성된 이슈를 확인하고 클로즈 하도록 하겠습니다.

**Comment by WonYong-Jang** [comment]
Linked pull request 테스트입니다.
pull request 요청 후 issue와 연결하여 pr이 정상적으로 merge 되었을 때 자동으로 issue가 close 되나 보네요.

**Comment by Quska45** [comment]
저희 처럼 스터디 할 땐 크게 사용할 일이 없겠지만 실제로 프로젝트에서 개발을 진행한다면 좋은 기능이겠네요. 프로젝트를 진행하다보면 issue에 쓰고 싶은 사항들이 많이 생기더라고요. 저희 개발 진행할 때도 이용해보면 좋겠습니다.
이번주 스터디 때 제가 회사에서 issue를 이용해서 개발을 진행했던 경험과 연결 지어서 봐보면 좋겠습니다.
테스트 해주셔서 감사합니다!
